name: L1-tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  L1-tests:
    name: Build and run unit tests
    runs-on: ubuntu-22.04

    steps:
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
          github-api-token: ''

      - name: Install packages
        run: >
          sudo apt update
          &&
          sudo apt install -y autoconf automake libtool pkg-config libgtest-dev libgmock-dev libdbus-1-dev build-essential g++ cmake valgrind lcov clang ninja-build

      - name: Checkout hdmicec
        uses: actions/checkout@v3
        with:
          path: hdmicec

      - name: Checkout googletest
        uses: actions/checkout@v3
        with:
          repository: google/googletest
          path: googletest
          ref: v1.15.0

      - name: Build googletest
        run: >
          cmake -G Ninja
          -S "$GITHUB_WORKSPACE/googletest"
          -B build/googletest
          -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install/usr"
          -DBUILD_TYPE=Debug
          -DBUILD_GMOCK=ON
          -DBUILD_SHARED_LIBS=OFF
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          &&
          cmake --build build/googletest -j8
          &&
          cmake --install build/googletest

      - name: Generate stub headers
        # Empty headers to mute errors
        run: >
          cd "$GITHUB_WORKSPACE/hdmicec"
          &&
          mkdir -p
          stubs/rdk/iarmbus
          stubs/ccec/drivers/iarmbus
          &&
          cd stubs
          &&
          touch
          rdk/iarmbus/libIARM.h
          rdk/iarmbus/libIBus.h
          rdk/iarmbus/libIBusDaemon.h
          ccec/drivers/iarmbus/CecIARMBusMgr.h
          &&
          ln -s ../../../mocks/hdmicec/hdmi_cec_driver.h ccec/drivers/hdmi_cec_driver.h
          
      - name: Build hdmicec
        run: >
          cd $GITHUB_WORKSPACE/hdmicec
          &&
          autoreconf -if
          &&
          CPPFLAGS="-I$GITHUB_WORKSPACE/hdmicec/mocks
          -I$GITHUB_WORKSPACE/hdmicec/stubs
          -I$GITHUB_WORKSPACE/install/usr/include"
          LDFLAGS="-L$GITHUB_WORKSPACE/install/usr/lib
          -fprofile-arcs -ftest-coverage"
          CXXFLAGS="-fprofile-arcs -ftest-coverage"
          ./configure --enable-l1tests
          &&
          make -j$(nproc) all
          &&
          cd tests/L1Tests && make all

      - name: List available tests
        run: >
          cd $GITHUB_WORKSPACE/hdmicec/tests/L1Tests
          &&
          LD_LIBRARY_PATH=$GITHUB_WORKSPACE/install/usr/lib:${LD_LIBRARY_PATH}
          ./run_L1Tests --gtest_list_tests

      - name: Run L1 Tests without valgrind
        run: >
          cd $GITHUB_WORKSPACE/hdmicec/tests/L1Tests
          &&
          LD_LIBRARY_PATH=$GITHUB_WORKSPACE/install/usr/lib:${LD_LIBRARY_PATH}
          GTEST_OUTPUT="json:$GITHUB_WORKSPACE/rdkL1TestResults.json"
          ./run_L1Tests --gtest_print_time=1 --gtest_output=json:$GITHUB_WORKSPACE/rdkL1TestResults.json || 
          (echo "Test execution failed or crashed" && exit 1)
          &&
          cp -rf $GITHUB_WORKSPACE/rdkL1TestResults.json $GITHUB_WORKSPACE/rdkL1TestResultsWithoutValgrind.json

      - name: Run L1 Tests with valgrind
        if: ${{ !env.ACT }}
        run: >
          cd $GITHUB_WORKSPACE/hdmicec/tests/L1Tests
          &&
          LD_LIBRARY_PATH=$GITHUB_WORKSPACE/install/usr/lib:${LD_LIBRARY_PATH}
          GTEST_OUTPUT="json:$GITHUB_WORKSPACE/rdkL1TestResults.json"
          make check-valgrind || (
          valgrind
          --tool=memcheck
          --log-file=$GITHUB_WORKSPACE/valgrind_log
          --leak-check=yes
          --show-reachable=yes
          --track-fds=yes
          --fair-sched=try
          ./run_L1Tests )
          &&
          cp -rf $GITHUB_WORKSPACE/rdkL1TestResults.json $GITHUB_WORKSPACE/rdkL1TestResultsWithValgrind.json

      - name: Generate coverage
        if: ${{ matrix.coverage == 'with-coverage' && !env.ACT }}
        run: >
          cd $GITHUB_WORKSPACE
          &&
          lcov -c
          -o coverage.info
          -d hdmicec
          &&
          lcov
          -r coverage.info
          '/usr/include/*'
          '*/install/usr/include/*'
          '*/stubs/*'
          '*/mocks/*'
          '*/googletest/*'
          '*/tests/*'
          '*/test_*.cpp'
          -o filtered_coverage.info
          &&
          genhtml
          -o coverage
          -t "hdmicec coverage"
          filtered_coverage.info

      - name: Upload artifacts
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-L1-hdmicec-${{ matrix.compiler }}-${{ matrix.coverage }}
          path: |
            coverage/
            valgrind_log
            rdkL1TestResultsWithoutValgrind.json
            rdkL1TestResultsWithValgrind.json
          if-no-files-found: warn
